name: 'Commit Message Checker'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - 'releases/*'
    paths-ignore:
      - '*/workflows/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '\[(BUGFIX|DOCS|FEATURE|TASK)\] .+$'
          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          excludeDescription: 'true'
      - name: Check Subject Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(.{60}[^ ]*).\n*'
          error: 'Subject too long (max 60)'
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '\s*(Implements|Contributes|Resolves|Fixes)\s*:?\s*(#\d+|github\.com\/axe007\/[a-z-.]*#\d+)'
          error: 'You need at least one "Implements|Contributes|Resolves|Fixes: #<issue number>" line.'
